### ISSUE TITLE
Wrong keyword argument 'file_paths' for fireball

### ISSUE THREAD

**Issue by JonasKru** [bobbyhiddn/Magi_CLI#36]
Just installed it and wanted to try it out, got the following error message at my first command:

```
TypeError: fireball() got an unexpected keyword argument 'file_paths'
```

**Comment by bobbyhiddn** [comment]
Hm. That must be due to the recent changes I made for aether_inquiry. I'll be sure to implement a process of testing how changes to cast effect spells in the future. Thanks for bringing it to my attention, and I apologize for harming your first experience with the tool! I'll post a revision shortly that should account for this issue. I'll comment on this thread when I've corrected it.

**Comment by bobbyhiddn** [comment]
It took a bit longer than I expected, and I'll be doing more thorough testing before releases in the future, but with v0.1.5 all issues should be resolved.

Plus, I added conversation history for aether-inquiry! I'll be updating the documentation when I introduce the .sanctum home folder feature.

Please try it out and let me know what you think.

**Comment by JonasKru** [comment]
Updated, and error is gone!
I look into the whole `.sanctum` stuff later and let you know if everything is running fine.
